language: ruby
node_js:
  - "8.10"
rvm:
  - 2.5.1
install:
  - gem install bundler -v '2.1.4'
before_script:
  - bundle install
script:
  - bundle exec jekyll build
notifications:
  email: false
branches:
  only:
    - master
after_success:
  - echo "Build was successful"
